version: 2

sources:
  - name: norm
    database: group3
    schema: norm
    tables:
     - name: t_employee
     - name: t_region

models:
  - name: stg_employee
    columns:
      - name: employee_id
        description: "A unique identifier for the employee"
        tests:
          - unique
          - not_null
      - name: employee_name
        description: "The name of the employee"
      - name: region
        description: "The region this employee is responsible for"
